# @package _global_

defaults:
  - override /data: robotwin
  - override /model: ahawam_ode
  - _self_

batch_size: 16
num_workers: 16
history_aware_batching: true

model:
  mot_checkpoint_mixed_attn: false
  teacher:
    checkpoint_path: path/to/step_045000.pt
  student:
    checkpoint_path: null

data:
  train:
    dataset_dirs:
      - path/to/robotwin2.0
    pretrained_norm_stats: path/to/dataset_stats.json
    text_embedding_cache_dir: path/to/text_embeds_cache/robotwin
  val:
    dataset_dirs:
      - path/to/robotwin2.0
    pretrained_norm_stats: path/to/dataset_stats.json
    text_embedding_cache_dir: path/to/text_embeds_cache/robotwin

output_dir: path/to/checkpoints/robotwin_ode/runs/train/${hydra:runtime.choices.task}-${now:%Y-%m-%d}_${now:%H-%M-%S}

wandb:
  enabled: true
  workspace: null
  project: ahawam
  name: robotwin_ahawam_ode
  group: null
  mode: online

lr_scheduler_type: "cosine"
learning_rate: 2e-5
num_epochs: 5
max_steps: null
log_every: 10
save_every: 2500
eval_every: 500

gradient_accumulation_steps: 4
weight_decay: 1e-2
resume: null
